In [1]:
from pathlib import Path
import os

PROJECT_ROOT = Path.cwd().parent

os.chdir(PROJECT_ROOT)
print("Project root:", PROJECT_ROOT)
print("Current working directory:", Path.cwd())

Project root: /Users/Local/REPOSITORIES/injury_risk_classifier
Current working directory: /Users/Local/REPOSITORIES/injury_risk_classifier

In [2]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
from pathlib import Path
import os 

%load_ext autoreload
%autoreload 2

from src.make_features import *

In [3]:
df = pd.read_csv("../injury_risk_classifier/data/interim/traffic_clean.csv")
df.head()

,Unnamed: 0,top_traffic_accident_offense,incident_address,geo_lon,geo_lat,tu1_driver_action,tu2_driver_action,tu1_vehicle_type,tu2_vehicle_type,tu1_driver_humancontribfactor,tu2_driver_humancontribfactor,tu1_pedestrian_action,seriously_injured,fatalities,tu2_pedestrian_action,road_description,road_condition,light_condition
0,0,TRAF - ACCIDENT,I25 HWYNB / W 6TH AVE,-105.013229,39.725677,No Contributing Action,No Contributing Action,Pickup Truck/Utility Van,Transit Bus,No Apparent Contributing Factor,No Apparent Contributing Factor,NaN,0.0,0.0,NaN,Non-Intersection,Dry,Daylight
1,1,TRAF - ACCIDENT,E 17TH AVE / N PENNSYLVANIA ST,-104.981084,39.743271,Failed to Yield ROW,No Contributing Action,Passenger Car/Passenger Van,SUV,No Apparent Contributing Factor,No Apparent Contributing Factor,NaN,0.0,0.0,NaN,At Intersection,Dry,Daylight
2,2,TRAF - ACCIDENT,I25 HWYSB / PARK AVEW,-104.994972,39.768330,Followed Too Closely,No Contributing Action,Passenger Car/Passenger Van,Passenger Car/Passenger Van,No Apparent Contributing Factor,No Apparent Contributing Factor,NaN,0.0,0.0,NaN,Non-Intersection,Dry,Daylight
3,3,TRAF - ACCIDENT - POLICE,I25 HWYNB / 20TH ST,-105.004334,39.760949,Followed Too Closely,No Contributing Action,Pickup Truck/Utility Van,Passenger Car/Passenger Van,Aggressive Driving,No Apparent Contributing Factor,NaN,0.0,0.0,NaN,Non-Intersection,Dry,Dark-Lighted
4,4,TRAF - ACCIDENT - HIT & RUN,W 37TH AVE / N PECOS ST,-105.006450,39.768054,NaN,NaN,Unknown (Hit and Run Only),Passenger Car/Passenger Van,NaN,NaN,NaN,0.0,0.0,NaN,Non-Intersection,Dry,Dark-Lighted

In [4]:
df.columns

Index(['Unnamed: 0', 'top_traffic_accident_offense', 'incident_address',
       'geo_lon', 'geo_lat', 'tu1_driver_action', 'tu2_driver_action',
       'tu1_vehicle_type', 'tu2_vehicle_type', 'tu1_driver_humancontribfactor',
       'tu2_driver_humancontribfactor', 'tu1_pedestrian_action',
       'seriously_injured', 'fatalities', 'tu2_pedestrian_action',
       'road_description', 'road_condition', 'light_condition'],
      dtype='str')

In [5]:
create_outcome(df)

,Unnamed: 0,top_traffic_accident_offense,incident_address,geo_lon,geo_lat,tu1_driver_action,tu2_driver_action,tu1_vehicle_type,tu2_vehicle_type,tu1_driver_humancontribfactor,tu2_driver_humancontribfactor,tu1_pedestrian_action,seriously_injured,fatalities,tu2_pedestrian_action,road_description,road_condition,light_condition,injured
0,0,TRAF - ACCIDENT,I25 HWYNB / W 6TH AVE,-105.013229,39.725677,No Contributing Action,No Contributing Action,Pickup Truck/Utility Van,Transit Bus,No Apparent Contributing Factor,No Apparent Contributing Factor,NaN,0.0,0.0,NaN,Non-Intersection,Dry,Daylight,0
1,1,TRAF - ACCIDENT,E 17TH AVE / N PENNSYLVANIA ST,-104.981084,39.743271,Failed to Yield ROW,No Contributing Action,Passenger Car/Passenger Van,SUV,No Apparent Contributing Factor,No Apparent Contributing Factor,NaN,0.0,0.0,NaN,At Intersection,Dry,Daylight,0
2,2,TRAF - ACCIDENT,I25 HWYSB / PARK AVEW,-104.994972,39.768330,Followed Too Closely,No Contributing Action,Passenger Car/Passenger Van,Passenger Car/Passenger Van,No Apparent Contributing Factor,No Apparent Contributing Factor,NaN,0.0,0.0,NaN,Non-Intersection,Dry,Daylight,0
3,3,TRAF - ACCIDENT - POLICE,I25 HWYNB / 20TH ST,-105.004334,39.760949,Followed Too Closely,No Contributing Action,Pickup Truck/Utility Van,Passenger Car/Passenger Van,Aggressive Driving,No Apparent Contributing Factor,NaN,0.0,0.0,NaN,Non-Intersection,Dry,Dark-Lighted,0
4,4,TRAF - ACCIDENT - HIT & RUN,W 37TH AVE / N PECOS ST,-105.006450,39.768054,NaN,NaN,Unknown (Hit and Run Only),Passenger Car/Passenger Van,NaN,NaN,NaN,0.0,0.0,NaN,Non-Intersection,Dry,Dark-Lighted,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282353,282353,TRAF - ACCIDENT,I25 HWYSB / W 23RD AVE,-105.016793,39.751285,Lane Violation,No Contributing Action,Passenger Car/Passenger Van,Passenger Car/Passenger Van,Distracted/Other Interior,No Apparent Contributing Factor,NaN,0.0,0.0,NaN,At Intersection,Dry,Daylight,0
282354,282354,TRAF - ACCIDENT - HIT & RUN,I70 HWYWB / N MONACO ST,-104.912882,39.778408,Careless Driving,No Contributing Action,SUV,Pickup Truck/Utility Van,Aggressive Driving,No Apparent Contributing Factor,NaN,0.0,0.0,NaN,Non-Intersection,Dry,Daylight,0
282355,282355,TRAF - ACCIDENT,50 BLOCK N HOLLY ST,-104.922176,39.717045,Followed Too Closely,No Contributing Action,Passenger Car/Passenger Van,Pickup Truck/Utility Van,No Apparent Contributing Factor,No Apparent Contributing Factor,NaN,0.0,0.0,NaN,Non-Intersection,Wet,Daylight,0
282356,282356,TRAF - ACCIDENT - HIT & RUN,20TH ST / ARAPAHOE ST,-104.990832,39.751590,Lane Violation,No Contributing Action,Passenger Car/Passenger Van,Passenger Car/Passenger Van,No Apparent Contributing Factor,No Apparent Contributing Factor,NaN,0.0,0.0,NaN,At Intersection,Dry,Dark-Lighted,0
282357,282357,TRAF - ACCIDENT - HIT & RUN,5190 N GRAY ST,-105.060105,39.790885,Too Fast for Conditions,NaN,Unknown (Hit and Run Only),NaN,No Apparent Contributing Factor,NaN,NaN,0.0,0.0,NaN,Non-Intersection,Icy W/Visible Icy Road Treatment,Daylight,0